# Generated by Django 4.2 on 2023-04-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('class_name', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('table_level', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datacheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('left_type', models.CharField(choices=[('sql_query', 'SQL query'), ('sql_expression', 'SQL expression'), ('expectation', 'Expectation')], max_length=30)),
                ('left_logic', models.TextField(blank=True, null=True)),
                ('left_column', models.CharField(blank=True, max_length=256, null=True)),
                ('left_expectation_parameters', models.JSONField(blank=True, null=True)),
                ('relation', models.CharField(blank=True, choices=[('eq', '='), ('ne', '!='), ('gt', '>'), ('lt', '<'), ('ge', '>='), ('le', '<=')], max_length=5, null=True)),
                ('right_type', models.CharField(blank=True, choices=[('sql_query', 'SQL query'), ('sql_expression', 'SQL expression'), ('number', 'Number'), ('string', 'String'), ('date', 'Date'), ('python_expression', 'Python expression'), ('expectation', 'Expectation')], max_length=30, null=True)),
                ('right_logic', models.TextField(blank=True, null=True)),
                ('right_number_value', models.FloatField(blank=True, null=True)),
                ('right_date_value', models.DateTimeField(blank=True, null=True)),
                ('right_object_value', models.JSONField(blank=True, null=True)),
                ('supports_warning', models.BooleanField(default=False)),
                ('warning_relation', models.CharField(blank=True, choices=[('eq', '='), ('ne', '!='), ('gt', '>'), ('lt', '<'), ('ge', '>='), ('le', '<=')], max_length=5, null=True)),
                ('warning_type', models.CharField(blank=True, choices=[('sql_query', 'SQL query'), ('sql_expression', 'SQL expression'), ('number', 'Number'), ('string', 'String'), ('date', 'Date'), ('python_expression', 'Python expression'), ('expectation', 'Expectation')], max_length=30, null=True)),
                ('warning_logic', models.TextField(blank=True, null=True)),
                ('warning_number_value', models.FloatField(blank=True, null=True)),
                ('warning_date_value', models.DateTimeField(blank=True, null=True)),
                ('warning_object_value', models.JSONField(blank=True, null=True)),
                ('left_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.dataset')),
                ('left_expectation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.expectation')),
                ('left_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_system', to='systems.system')),
                ('right_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_system', to='systems.system')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('warning_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warning_system', to='systems.system')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('finished', 'Finished'), ('error', 'Error')], default='new', max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('failed', 'Failed')], max_length=20, null=True)),
                ('left_value_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('object', 'Object')], max_length=20)),
                ('left_string_value', models.CharField(blank=True, max_length=4096, null=True)),
                ('left_number_value', models.FloatField(blank=True, null=True)),
                ('left_date_value', models.DateTimeField(blank=True, null=True)),
                ('left_object_value', models.JSONField(blank=True, null=True)),
                ('left_column', models.CharField(blank=True, max_length=256, null=True)),
                ('left_expectation_parameters', models.JSONField(blank=True, null=True)),
                ('relation', models.CharField(blank=True, choices=[('eq', '='), ('ne', '!='), ('gt', '>'), ('lt', '<'), ('ge', '>='), ('le', '<=')], max_length=5, null=True)),
                ('right_value_type', models.CharField(blank=True, choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('object', 'Object')], max_length=20, null=True)),
                ('right_string_value', models.CharField(blank=True, max_length=4096, null=True)),
                ('right_number_value', models.FloatField(blank=True, null=True)),
                ('right_date_value', models.DateTimeField(blank=True, null=True)),
                ('right_object_value', models.JSONField(blank=True, null=True)),
                ('warning_relation', models.CharField(blank=True, choices=[('eq', '='), ('ne', '!='), ('gt', '>'), ('lt', '<'), ('ge', '>='), ('le', '<=')], max_length=5, null=True)),
                ('warning_value_type', models.CharField(blank=True, choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('object', 'Object')], max_length=20, null=True)),
                ('warning_string_value', models.CharField(blank=True, max_length=4096, null=True)),
                ('warning_number_value', models.FloatField(blank=True, null=True)),
                ('warning_date_value', models.DateTimeField(blank=True, null=True)),
                ('warning_object_value', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datacheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.datacheck')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.environment')),
                ('left_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.dataset')),
                ('left_expectation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.expectation')),
                ('left_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_instance', to='systems.instance')),
                ('left_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.dbtable')),
                ('right_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_instance', to='systems.instance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warning_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warning_instance', to='systems.instance')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
