# Generated by Django 3.0.1 on 2020-01-02 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("systems", "0001_initial"),
        ("taggit", "0003_taggeditem_add_unique_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Datacheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("weight", models.IntegerField(default=0)),
                (
                    "left_type",
                    models.IntegerField(
                        choices=[
                            (0, "SQL query"),
                            (1, "SQL expression"),
                            (2, "Number"),
                            (3, "String"),
                            (4, "Date"),
                            (5, "Python expression"),
                        ]
                    ),
                ),
                ("left_logic", models.TextField()),
                (
                    "relation",
                    models.IntegerField(
                        choices=[
                            (0, "="),
                            (1, "!="),
                            (2, ">"),
                            (3, "<"),
                            (4, ">="),
                            (5, "<="),
                        ]
                    ),
                ),
                (
                    "right_type",
                    models.IntegerField(
                        choices=[
                            (0, "SQL query"),
                            (1, "SQL expression"),
                            (2, "Number"),
                            (3, "String"),
                            (4, "Date"),
                            (5, "Python expression"),
                        ]
                    ),
                ),
                ("right_logic", models.TextField()),
                ("supports_warning", models.BooleanField(default=False)),
                (
                    "warning_relation",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "="),
                            (1, "!="),
                            (2, ">"),
                            (3, "<"),
                            (4, ">="),
                            (5, "<="),
                        ],
                        null=True,
                    ),
                ),
                (
                    "warning_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "SQL query"),
                            (1, "SQL expression"),
                            (2, "Number"),
                            (3, "String"),
                            (4, "Date"),
                            (5, "Python expression"),
                        ],
                        null=True,
                    ),
                ),
                ("warning_logic", models.TextField(blank=True, null=True)),
                (
                    "left_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="left_system",
                        to="systems.System",
                    ),
                ),
                (
                    "right_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_system",
                        to="systems.System",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={"ordering": ("-pk",),},
        ),
        migrations.CreateModel(
            name="EnvironmentStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_start_time", models.DateTimeField(null=True)),
                ("last_end_time", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("RUNNING", "Running"),
                            ("FINISHED", "Finished"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "datacheck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checks.Datacheck",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="systems.Environment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("RUNNING", "Running"),
                            ("FINISHED", "Finished"),
                            ("ERROR", "Error"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("left_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "right_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "warning_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "datacheck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checks.Datacheck",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="systems.Environment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-pk",),},
        ),
    ]
