# Generated by Django 2.2.8 on 2019-12-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0004_datacheck_tags"),
    ]

    operations = [
        migrations.RemoveField(model_name="datacheck", name="group",),
        migrations.AlterField(
            model_name="checkrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("RUNNING", "Running"),
                    ("FINISHED", "Finished"),
                    ("ERROR", "Error"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(name="CheckGroup",),
    ]
