# Generated by Django 3.0.1 on 2020-01-02 20:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={"ordering": ("-pk",),},
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True, unique=True)),
                (
                    "application",
                    models.IntegerField(
                        choices=[
                            (0, "Postgresql"),
                            (1, "Redshift"),
                            (2, "MySQL"),
                            (3, "Snowflake"),
                        ]
                    ),
                ),
            ],
            options={"ordering": ("-pk",),},
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=100, null=True)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("db", models.CharField(blank=True, max_length=100, null=True)),
                ("schema", models.CharField(blank=True, max_length=100, null=True)),
                ("login", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "extra_json",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="systems.Environment",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="systems.System"
                    ),
                ),
            ],
            options={"ordering": ("-pk",),},
        ),
        migrations.CreateModel(
            name="DbTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("fullname", models.CharField(max_length=255)),
                ("schema", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("last_profiling_at", models.DateTimeField(null=True)),
                ("rows", models.IntegerField(null=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="systems.Environment",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="systems.System"
                    ),
                ),
            ],
            options={
                "ordering": ("system", "environment", "fullname"),
                "unique_together": {("system", "environment", "fullname")},
            },
        ),
    ]
