# Generated by Django 4.2 on 2023-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbtable",
            name="deleted_at",
        ),
        migrations.AddField(
            model_name="dbtable",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="dbtable",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
