# Generated by Django 2.2.9 on 2019-12-27 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0005_auto_20191112_1138"),
    ]

    operations = [
        migrations.CreateModel(
            name="DbTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("fullname", models.CharField(max_length=255)),
                ("schema", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="systems.System"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
