# Generated by Django 2.2.9 on 2019-12-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0006_dbtable"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtable",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="systems.Environment"
            ),
            preserve_default=False,
        ),
    ]
