# Generated by Django 2.2.9 on 2019-12-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0007_dbtable_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtable",
            name="last_profiling_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="dbtable", name="rows", field=models.IntegerField(null=True),
        ),
    ]
