# Generated by Django 3.0.1 on 2020-01-01 19:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0008_auto_20191229_1451"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dbtable", options={"ordering": ("system", "environment", "fullname")},
        ),
        migrations.AlterField(
            model_name="instance",
            name="extra_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
