# Generated by Django 3.0.1 on 2020-01-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0009_auto_20200101_1951"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dbtable", unique_together={("system", "environment", "fullname")},
        ),
    ]
