# Generated by Django 3.0.1 on 2020-01-02 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("RUNNING", "Running"),
                            ("FINISHED", "Finished"),
                            ("ERROR", "Error"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.FileField(max_length=255, upload_to="profiling_reports"),
                ),
                ("rows", models.IntegerField(null=True)),
                (
                    "dbtable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="systems.DbTable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-pk",),},
        ),
    ]
