# Generated by Django 4.2 on 2023-04-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableprofile",
            name="profiler",
            field=models.CharField(
                choices=[("pandas", "Pandas Profiler"), ("spark", "Spark Profiler"), ("gx", "GX Profiler")],
                default="pandas",
                max_length=20,
            ),
        ),
    ]
