# Generated by Django 2.2.9 on 2019-12-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableprofile",
            name="result",
            field=models.FileField(max_length=255, upload_to=""),
        ),
    ]
