# Generated by Django 2.2.9 on 2019-12-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0002_auto_20191228_1706"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tableprofile", options={"ordering": ("-pk",)},
        ),
    ]
