# Generated by Django 4.2 on 2023-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiling", "0002_tableprofile_profiler"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableprofile",
            name="variables",
            field=models.IntegerField(null=True),
        ),
    ]
