# Generated by Django 2.2.9 on 2019-12-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0003_auto_20191229_1044"),
    ]

    operations = [
        migrations.RemoveField(model_name="tableprofile", name="environment",),
        migrations.RemoveField(model_name="tableprofile", name="system",),
    ]
