# Generated by Django 3.0.1 on 2020-01-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0004_auto_20191229_1138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableprofile",
            name="result",
            field=models.FileField(max_length=255, upload_to="profiling_reports"),
        ),
    ]
