name: CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "main", "develop" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/local.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0


  pytest:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Build the Stack
        run:  docker-compose -f docker-compose-develop.yml build

      - name: Run DB Migrations
        run:  docker-compose -f docker-compose-develop.yml run --rm inspector python manage.py migrate

      - name: Run Django Tests
        run:  docker-compose -f docker-compose-develop.yml run inspector pytest

      - name: Tear down the Stack
        run:  docker-compose -f docker-compose-develop.yml down
