name: docker

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    permissions:
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1


      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Inspector image
        id: release_build
        uses: docker/build-push-action@v4
        with:
          outputs: "type=registry,push=true"
          provenance: false
          platforms: linux/amd64,linux/arm64
          file: compose/production/inspector/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/inspector:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/inspector:${{ github.ref_name }}
            ghcr.io/${{ env.REPO_OWNER }}/inspector:latest

      - name: Inspector worker image
        id: release_build_worker
        uses: docker/build-push-action@v4
        with:
          outputs: "type=registry,push=true"
          provenance: false
          platforms: linux/amd64,linux/arm64
          file: compose/production/inspector/Dockerfile
          build-args: |
            BUILD_ENVIRONMENT=worker
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/inspector-worker:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/inspector-worker:${{ github.ref_name }}
            ghcr.io/${{ env.REPO_OWNER }}/inspector-worker:latest
